title: Graham Riley
author: grahamri
email: grahamri@kainos.com
description: > # this means to ignore newlines until "baseurl:"
  Crafting meaningful digital experiences.

# social links
twitter_username: grahamriley79
github_username:  grahamri

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
